#!/usr/bin/env ruby

cmd = ARGV[0]
bin = ARGV[1]
src = ARGV[2]

case cmd
when "make"
    %x[mkdir bin]
    %x[ghc -o bin/#{bin} --make #{src}.hs]
    %x[rm #{src}.hi #{src}.o]
when "clean"
    %x[rm -rf bin/]
else
    puts "Wrong command, try 'make' or 'clean'"
end
